/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import java.util.List;

/**
 * DTO class for "Addresses"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class AddressesDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   userId;
    private String   label;
    private String   recipientName;
    private Integer   phoneId;
    private String   addressLine;
    private Integer   provinceId;
    private Integer   countryId;
    private String   postalCode;
    private Boolean   isDefault;
    private Date   createdAt;

    //--- LINKS ( RELATIONSHIPS )
    private CountriesDTO countries;
    private ProvincesDTO provinces;
    private UsersDTO users;
    private List<OrdersDTO> listOfOrders;
    private UserPhoneNumbersDTO userPhoneNumbers;

}