/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

/**
 * DTO class for "Attributes"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class AttributesDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private String   name;
    private String   code;
    private String   valueType;
    private Boolean   isVariantDefining;

    //--- LINKS ( RELATIONSHIPS )
    private List<AttributeOptionsDTO> listOfAttributeOptions;
    private List<ProductAttributeOptionsDTO> listOfProductAttributeOptions;
    private List<ProductAttributeValuesDTO> listOfProductAttributeValues;

}