/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * DTO class for "Coupons"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class CouponsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private String   code;
    private String   discountType;
    private BigDecimal   value;
    private BigDecimal   minSubtotal;
    private Integer   usageLimit;
    private Integer   usedCount;
    private Integer   perUserLimit;
    private Date   validFrom;
    private Date   validTo;
    private Boolean   isActive;

    //--- LINKS ( RELATIONSHIPS )
    private List<CouponRedemptionsDTO> listOfCouponRedemptions;
    private List<OrdersDTO> listOfOrders;

}