/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * DTO class for "Orders"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class OrdersDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id;

    //--- OTHER DATA FIELDS 
    private String   orderCode;
    private Integer   userId;
    private Integer   addressId;
    private Integer   couponId;
    private BigDecimal   subtotal;
    private BigDecimal   discount;
    private BigDecimal   shippingFee;
    private BigDecimal   total;
    private String   currency;
    private String   status;
    private Date   createdAt;
    private Date   updatedAt;
    private Date   expiresAt;

    //--- LINKS ( RELATIONSHIPS )
    private List<OrderPaymentsDTO> listOfOrderPayments;
    private AddressesDTO addresses;
    private List<OrderEventsDTO> listOfOrderEvents;
    private CouponsDTO coupons;
    private List<StockReservationsDTO> listOfStockReservations;
    private List<CouponRedemptionsDTO> listOfCouponRedemptions;
    private UsersDTO users;
    private List<OrderItemsDTO> listOfOrderItems;

}