/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

/**
 * DTO class for "ProductVariantImages"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class ProductVariantImagesDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   variantId;
    private String   url;
    private Boolean   isPrimary;
    private Integer   sortOrder;
    private Date   createdAt;

    //--- LINKS ( RELATIONSHIPS )
    private ProductVariantsDTO productVariants;

}