/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * DTO class for "Products"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class ProductsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private String   sku;
    private String   name;
    private String   slug;
    private String   shortDescription;
    private String   longDescription;
    private Integer   categoryId;
    private BigDecimal   price;
    private Boolean   hasVariants;
    private Boolean   isPublished;
    private Date   createdAt;
    private Date   updatedAt;

    //--- LINKS ( RELATIONSHIPS )
    private CategoriesDTO categories;
    private List<ProductVariantsDTO> listOfProductVariants;
    private List<ProductReviewsDTO> listOfProductReviews;
    private List<ProductAttributeOptionsDTO> listOfProductAttributeOptions;
    private List<ProductAttributeValuesDTO> listOfProductAttributeValues;
    private List<ProductRelationsDTO> listOfProductRelations;
    private List<WishlistItemsDTO> listOfWishlistItems;
    private List<ProductImagesDTO> listOfProductImages;
    private List<ProductRelationsDTO> listOfProductRelations2;
    private List<VariantOptionGroupsDTO> listOfVariantOptionGroups;

}