/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

/**
 * DTO class for "ShippingRates"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class ShippingRatesDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   shippingZoneId;
    private BigDecimal   minWeight;
    private BigDecimal   maxWeight;
    private BigDecimal   price;
    private String   carrier;
    private String   serviceLevel;

    //--- LINKS ( RELATIONSHIPS )
    private ShippingZonesDTO shippingZones;

}