/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

/**
 * DTO class for "StockReceiptLines"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class StockReceiptLinesDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   receiptId;
    private Integer   variantId;
    private Integer   warehouseId;
    private Integer   quantity;
    private BigDecimal   costPrice;

    //--- LINKS ( RELATIONSHIPS )
    private StockReceiptsDTO stockReceipts;
    private ProductVariantsDTO productVariants;
    private WarehousesDTO warehouses;

}