/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import java.util.List;

/**
 * DTO class for "StockReceipts"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class StockReceiptsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private String   receiptNo;
    private Date   receivedAt;
    private Integer   createdBy;
    private Date   createdAt;

    //--- LINKS ( RELATIONSHIPS )
    private List<StockReceiptLinesDTO> listOfStockReceiptLines;
    private UsersDTO users;

}