/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import java.util.List;

/**
 * DTO class for "Users"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class UsersDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private String   email;
    private String   passwordHash;
    private String   fullName;
    private Date   dateOfBirth;
    private String   gender;
    private Boolean   isActive;
    private Date   createdAt;
    private Date   updatedAt;

    //--- LINKS ( RELATIONSHIPS )
    private List<ShoppingCartsDTO> listOfShoppingCarts;
    private List<StockReceiptsDTO> listOfStockReceipts;
    private List<ProductReviewsDTO> listOfProductReviews;
    private List<UserPhoneNumbersDTO> listOfUserPhoneNumbers;
    private List<OrdersDTO> listOfOrders;
    private List<UserRolesDTO> listOfUserRoles;
    private List<OrderEventsDTO> listOfOrderEvents;
    private List<WishlistsDTO> listOfWishlists;
    private List<CouponRedemptionsDTO> listOfCouponRedemptions;
    private List<AddressesDTO> listOfAddresses;
    private List<AuditLogsDTO> listOfAuditLogs;

}