/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import java.util.List;

/**
 * DTO class for "UserPhoneNumbers"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class UserPhoneNumbersDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   userId;
    private String   phoneNumber;
    private String   phoneType;
    private Boolean   isPrimary;
    private Date   createdAt;

    //--- LINKS ( RELATIONSHIPS )
    private List<AddressesDTO> listOfAddresses;
    private UsersDTO users;

}