/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

/**
 * DTO class for "UserRoles"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class UserRolesDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   userId;
    private Integer   roleId;
    private Date   createdAt;

    //--- LINKS ( RELATIONSHIPS )
    private UsersDTO users;
    private RolesDTO roles;

}