/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

/**
 * DTO class for "VariantOptionGroups"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class VariantOptionGroupsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   productId;
    private String   name;
    private Integer   position;
    private Boolean   isRequired;

    //--- LINKS ( RELATIONSHIPS )
    private List<VariantOptionValuesDTO> listOfVariantOptionValues;
    private ProductsDTO products;

}