/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import java.util.List;

/**
 * DTO class for "Warehouses"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class WarehousesDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private String   code;
    private String   name;
    private String   address;
    private String   phone;
    private Boolean   isActive;
    private Date   createdAt;

    //--- LINKS ( RELATIONSHIPS )
    private List<StockReservationsDTO> listOfStockReservations;
    private List<InventoryTransactionsDTO> listOfInventoryTransactions;
    private List<StockReceiptLinesDTO> listOfStockReceiptLines;
    private List<InventoryLevelsDTO> listOfInventoryLevels;

}