version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.11.0  # Official from Docker Hub
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:alpine 
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog  # Latest stable
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  elasticsearch_data:
  redis_data:

networks:
  app-network:
    driver: bridge