/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.inventory.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

import com.mijimoto.ECommerce.catalogue.persistence.entities.ProductVariants;

import jakarta.persistence.*;

/**
 * JPA entity class for "InventoryLevels"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="inventory_levels", schema="dbo", catalog="EcommerceDB" )
public class InventoryLevels implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="variant_id", nullable=false)
    private Integer          variantId    ;

    @Column(name="warehouse_id", nullable=false)
    private Integer          warehouseId    ;

    @Column(name="quantity_on_hand", nullable=false)
    private Integer          quantityOnHand    ;

    @Column(name="reserved_quantity", nullable=false)
    private Integer          reservedQuantity    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated", nullable=false)
    private Date             lastUpdated    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="variant_id", referencedColumnName="id", insertable=false, updatable=false)
    private ProductVariants productVariants;

    @ManyToOne
    @JoinColumn(name="warehouse_id", referencedColumnName="id", insertable=false, updatable=false)
    private Warehouses warehouses;

}