/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.inventory.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

import com.mijimoto.ECommerce.catalogue.persistence.entities.ProductVariants;

import jakarta.persistence.*;

/**
 * JPA entity class for "InventoryTransactions"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="inventory_transactions", schema="dbo", catalog="EcommerceDB" )
public class InventoryTransactions implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id;

    //--- OTHER DATA FIELDS 
    @Column(name="variant_id", nullable=false)
    private Integer          variantId    ;

    @Column(name="warehouse_id")
    private Integer          warehouseId    ;

    @Column(name="quantity_change", nullable=false)
    private Integer          quantityChange    ;

    @Column(name="reason", length=255)
    private String           reason    ;

    @Column(name="reference", length=255)
    private String           reference    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="variant_id", referencedColumnName="id", insertable=false, updatable=false)
    private ProductVariants productVariants;

    @ManyToOne
    @JoinColumn(name="warehouse_id", referencedColumnName="id", insertable=false, updatable=false)
    private Warehouses warehouses;

}