/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.inventory.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import java.util.List;

import com.mijimoto.ECommerce.user.persistence.entities.Users;

import jakarta.persistence.*;

/**
 * JPA entity class for "StockReceipts"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="stock_receipts", schema="dbo", catalog="EcommerceDB" )
public class StockReceipts implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="receipt_no", nullable=false, length=255)
    private String           receiptNo    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="received_at", nullable=false)
    private Date             receivedAt    ;

    @Column(name="created_by")
    private Integer          createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="stockReceipts")
    private List<StockReceiptLines> listOfStockReceiptLines;

    @ManyToOne
    @JoinColumn(name="created_by", referencedColumnName="id", insertable=false, updatable=false)
    private Users      users;

}