/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.inventory.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Warehouses"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="warehouses", schema="dbo", catalog="EcommerceDB" )
public class Warehouses implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="code", nullable=false, length=100)
    private String           code    ;

    @Column(name="name", nullable=false, length=255)
    private String           name    ;

    @Column(name="address", length=1000)
    private String           address    ;

    @Column(name="phone", length=50)
    private String           phone    ;

    @Column(name="is_active", nullable=false)
    private Boolean          isActive    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="warehouses")
    private List<StockReservations> listOfStockReservations;

    @OneToMany(mappedBy="warehouses")
    private List<InventoryTransactions> listOfInventoryTransactions;

    @OneToMany(mappedBy="warehouses")
    private List<StockReceiptLines> listOfStockReceiptLines;

    @OneToMany(mappedBy="warehouses")
    private List<InventoryLevels> listOfInventoryLevels;

}