/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.order.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "OrderPayments"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="order_payments", schema="dbo", catalog="EcommerceDB" )
public class OrderPayments implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id;

    //--- OTHER DATA FIELDS 
    @Column(name="order_id", nullable=false)
    private Long             orderId    ;

    @Column(name="provider", nullable=false, length=100)
    private String           provider    ;

    @Column(name="provider_transaction_id", length=255)
    private String           providerTransactionId    ;

    @Column(name="amount", nullable=false)
    private BigDecimal       amount    ;

    @Column(name="currency", length=10)
    private String           currency    ;

    @Column(name="status", nullable=false, length=50)
    private String           status    ;

    @Column(name="raw_response", length=2147483647)
    private String           rawResponse    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="order_id", referencedColumnName="id", insertable=false, updatable=false)
    private Orders     orders;

}