/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.order.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.mijimoto.ECommerce.inventory.persistence.entities.StockReservations;
import com.mijimoto.ECommerce.user.persistence.entities.Addresses;
import com.mijimoto.ECommerce.user.persistence.entities.Users;

import jakarta.persistence.*;

/**
 * JPA entity class for "Orders"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="orders", schema="dbo", catalog="EcommerceDB" )
public class Orders implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id;

    //--- OTHER DATA FIELDS 
    @Column(name="order_code", nullable=false, length=100)
    private String           orderCode    ;

    @Column(name="user_id", nullable=false)
    private Integer          userId    ;

    @Column(name="address_id", nullable=false)
    private Integer          addressId    ;

    @Column(name="coupon_id")
    private Integer          couponId    ;

    @Column(name="subtotal", nullable=false)
    private BigDecimal       subtotal    ;

    @Column(name="discount", nullable=false)
    private BigDecimal       discount    ;

    @Column(name="shipping_fee", nullable=false)
    private BigDecimal       shippingFee    ;

    @Column(name="total", nullable=false)
    private BigDecimal       total    ;

    @Column(name="currency", length=10)
    private String           currency    ;

    @Column(name="status", nullable=false, length=50)
    private String           status    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date             updatedAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expires_at")
    private Date             expiresAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="orders")
    private List<OrderPayments> listOfOrderPayments;

    @ManyToOne
    @JoinColumn(name="address_id", referencedColumnName="id", insertable=false, updatable=false)
    private Addresses  addresses;

    @OneToMany(mappedBy="orders")
    private List<OrderEvents> listOfOrderEvents;

    @ManyToOne
    @JoinColumn(name="coupon_id", referencedColumnName="id", insertable=false, updatable=false)
    private Coupons    coupons;

    @OneToMany(mappedBy="orders")
    private List<StockReservations> listOfStockReservations;

    @OneToMany(mappedBy="orders")
    private List<CouponRedemptions> listOfCouponRedemptions;

    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id", insertable=false, updatable=false)
    private Users      users;

    @OneToMany(mappedBy="orders")
    private List<OrderItems> listOfOrderItems;

}