/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.order.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

import com.mijimoto.ECommerce.catalogue.persistence.entities.ProductVariants;

import jakarta.persistence.*;

/**
 * JPA entity class for "OrderItems"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="order_items", schema="dbo", catalog="EcommerceDB" )
public class OrderItems implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id;

    //--- OTHER DATA FIELDS 
    @Column(name="order_id", nullable=false)
    private Long             orderId    ;

    @Column(name="variant_id", nullable=false)
    private Integer          variantId    ;

    @Column(name="product_snapshot_name", length=255)
    private String           productSnapshotName    ;

    @Column(name="sku_snapshot", length=100)
    private String           skuSnapshot    ;

    @Column(name="unit_price", nullable=false)
    private BigDecimal       unitPrice    ;

    @Column(name="quantity", nullable=false)
    private Integer          quantity    ;

    @Column(name="line_total", nullable=false)
    private BigDecimal       lineTotal    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="variant_id", referencedColumnName="id", insertable=false, updatable=false)
    private ProductVariants productVariants;

    @ManyToOne
    @JoinColumn(name="order_id", referencedColumnName="id", insertable=false, updatable=false)
    private Orders     orders;

}