/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.order.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import java.util.List;

import com.mijimoto.ECommerce.user.persistence.entities.Users;

import jakarta.persistence.*;

/**
 * JPA entity class for "ShoppingCarts"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="shopping_carts", schema="dbo", catalog="EcommerceDB" )
public class ShoppingCarts implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="user_id", nullable=false)
    private Integer          userId    ;

    @Column(name="coupon_id")
    private Integer          couponId    ;

    @Column(name="is_active", nullable=false)
    private Boolean          isActive    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date             updatedAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id", insertable=false, updatable=false)
    private Users      users;

    @OneToMany(mappedBy="shoppingCarts")
    private List<CartItems> listOfCartItems;

}