/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.customer.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

import com.mijimoto.ECommerce.catalogue.rest.dto.ProductsDTO;
import com.mijimoto.ECommerce.user.rest.dto.UsersDTO;

/**
 * DTO class for "ProductReviews"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class ProductReviewsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id;

    //--- OTHER DATA FIELDS 
    private Integer   productId;
    private Integer   userId;
    private Byte   rating;
    private String   title;
    private String   content;
    private String   status;
    private Date   createdAt;

    //--- LINKS ( RELATIONSHIPS )
    private ProductsDTO products;
    private UsersDTO users;

}