/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.customer.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import java.util.List;

import com.mijimoto.ECommerce.user.rest.dto.UsersDTO;

/**
 * DTO class for "Wishlists"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class WishlistsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   userId;
    private Date   createdAt;

    //--- LINKS ( RELATIONSHIPS )
    private List<WishlistItemsDTO> listOfWishlistItems;
    private UsersDTO users;

}