/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.customer.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

import com.mijimoto.ECommerce.catalogue.persistence.entities.Products;
import com.mijimoto.ECommerce.user.persistence.entities.Users;

import jakarta.persistence.*;

/**
 * JPA entity class for "ProductReviews"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="product_reviews", schema="dbo", catalog="EcommerceDB" )
public class ProductReviews implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id;

    //--- OTHER DATA FIELDS 
    @Column(name="product_id", nullable=false)
    private Integer          productId    ;

    @Column(name="user_id", nullable=false)
    private Integer          userId    ;

    @Column(name="rating", nullable=false)
    private Byte             rating    ;

    @Column(name="title", length=255)
    private String           title    ;

    @Column(name="content", length=2147483647)
    private String           content    ;

    @Column(name="status", nullable=false, length=20)
    private String           status    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products;

    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id", insertable=false, updatable=false)
    private Users      users;

}