/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.customer.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

import com.mijimoto.ECommerce.catalogue.persistence.entities.Products;

import jakarta.persistence.*;

/**
 * JPA entity class for "WishlistItems"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="wishlist_items", schema="dbo", catalog="EcommerceDB" )
public class WishlistItems implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="wishlist_id", nullable=false)
    private Integer          wishlistId    ;

    @Column(name="product_id", nullable=false)
    private Integer          productId    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="added_at", nullable=false)
    private Date             addedAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="wishlist_id", referencedColumnName="id", insertable=false, updatable=false)
    private Wishlists  wishlists;

    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products;

}