/*
 * Created on 2025-10-25 ( 20:29:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.user.rest.services;

import java.util.List;
import java.util.Optional;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.http.HttpStatus;

import com.mijimoto.ECommerce.user.persistence.entities.Roles;
import com.mijimoto.ECommerce.user.persistence.repositories.RolesRepository;
import com.mijimoto.ECommerce.user.rest.dto.RolesDTO;
import com.mijimoto.ECommerce.common.rest.services.GenericService;


/**
 * REST service for entity "Roles" <br>
 *
 * This service provides all the necessary operations required by the REST controller <br>
 * Enhanced to handle foreign key relationships with proper validation and error handling using
 * ResponseStatusException (Option A).
 *
 * @author Telosys
 *
 */
@Service
@Transactional
public class RolesService extends GenericService<Roles, RolesDTO> {

    private static final Logger logger = LoggerFactory.getLogger(RolesService.class);

    private final RolesRepository repository;


    /**
     * Constructor (usable for Dependency Injection)
     *
     * @param repository the repository to be injected
     */
    public RolesService(RolesRepository repository) {
        super(Roles.class, RolesDTO.class);
        this.repository = repository;
    }
    
    /**
     * Returns the entity ID object from the given DTO
     *
     * @param dto the DTO
     * @return the entity ID
     */
    private Integer getEntityId(RolesDTO dto) {
        return dto.getId();
    }

    /**
     * Validates foreign key references before persisting
     *
     * @param dto the DTO to validate
     * @throws ResponseStatusException if any FK reference is invalid (HTTP 400)
     */
    private void validateForeignKeyReferences(RolesDTO dto) {
    }

    /**
     * Finds all occurrences of the entity
     *
     * @return list of DTOs
     */
    public List<RolesDTO> findAll() {
        logger.debug("findAll()");
        Iterable<Roles> all = repository.findAll();
        return entityListToDtoList(all);
    }

    /**
     * Finds the entity identified by the given PK
     *
     * @param id 
     * @return the DTO or null if not found
     */
    public RolesDTO findById(Integer id) {
        Integer entityId = id;
        logger.debug("findById({})", entityId);
        Optional<Roles> optionalEntity = repository.findById(entityId);
        return entityToDto(optionalEntity);
    }

    /**
     * Finds the entity by ID or throws exception
     *
     * @param id 
     * @return the DTO
     * @throws ResponseStatusException if not found (HTTP 404)
     */
    public RolesDTO findByIdOrThrow(Integer id) {
        Integer entityId = id;
        logger.debug("findByIdOrThrow({})", entityId);
        Optional<Roles> optionalEntity = repository.findById(entityId);
        if (!optionalEntity.isPresent()) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                    String.format("Roles with id %s not found", entityId));
        }
        return entityToDto(optionalEntity.get());
    }

    /**
     * Creates the given entity <br>
     * Validates foreign key references before creating
     *
     * @param dto the DTO to create
     * @return the created DTO with generated ID (if applicable)
     * @throws ResponseStatusException if FK validation fails (HTTP 400)
     */
    public RolesDTO create(RolesDTO dto) {
        logger.debug("create({})", dto);
        
        // Validate DTO
        validateDto(dto);
        
        // Validate foreign key references FIRST
        validateForeignKeyReferences(dto);
        
        // Auto-generated Primary Key - always create
        Roles entity = dtoToEntity(dto);
        Roles saved = repository.save(entity);
        return entityToDto(saved);
    }

    /**
     * Updates partially the given entity if it exists <br>
     * Only updates non-null fields from DTO <br>
     * Validates foreign key references for non-null FK fields
     *
     * @param id 
     * @param dto the DTO with fields to update
     * @return the updated DTO
     * @throws ResponseStatusException if entity not found (404) or FK validation fails (400)
     */
    public RolesDTO partialUpdate(Integer id, RolesDTO dto) {
        Integer entityId = id;
        logger.debug("partialUpdate({}, {})", entityId, dto);
        
        Optional<Roles> optionalEntity = repository.findById(entityId);
        if (!optionalEntity.isPresent()) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                    String.format("Roles with id %s not found", entityId));
        }
        
        // Validate foreign key references for non-null FK fields
        validateForeignKeyReferences(dto);
        
        Roles entity = optionalEntity.get();
        
        // Use GenericService's updateEntityFromDto which skips nulls
        updateEntityFromDto(entity, dto);
        
        Roles updated = repository.save(entity);
        return entityToDto(updated);
    }

    /**
     * Deletes an entity by its PK
     *
     * @param id 
     * @throws ResponseStatusException if entity not found (HTTP 404)
     */
    public void deleteById(Integer id) {
        Integer entityId = id;
        logger.debug("deleteById({})", entityId);
        
        if (!repository.existsById(entityId)) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                    String.format("Roles with id %s not found", entityId));
        }
        
        repository.deleteById(entityId);
    }

    /**
     * Checks if entity exists by ID
     *
     * @param id 
     * @return true if exists, false otherwise
     */
    public boolean existsById(Integer id) {
        Integer entityId = id;
        return repository.existsById(entityId);
    }

    // -----------------------------------------------------------------------------------------
    // Specific "finders" for foreign key relationships
    // -----------------------------------------------------------------------------------------

    // -----------------------------------------------------------------------------------------
    // DEPRECATED METHODS - Use the improved methods above instead
    // These are kept for backward compatibility but should not be used in new code
    // -----------------------------------------------------------------------------------------
    
    /*
    @Deprecated
    public void save(Integer id, RolesDTO dto) {
        // DEPRECATED: This method has been replaced by update() which returns the updated entity
        // and provides better error handling with exceptions
        Integer entityId = id;
        logger.warn("DEPRECATED: save() called with entityId: {}. Use update() instead.", entityId);
        
        validateForeignKeyReferences(dto);
        
        // Force PK in DTO
        dto.setId(id);
        
        repository.save(dtoToEntity(dto));
    }
    */

    /* ------------------------------------------------------------------
     * The full `update()` method was intentionally moved to the end of
     * the file and commented out as requested. Keep it commented while
     * preserving the implementation for easy restoration or reference.
     * ------------------------------------------------------------------ */

   
    /**
     * Updates the given entity if it exists <br>
     * Validates foreign key references before updating
     *
     * @param dto the DTO to update
     * @return the updated DTO
     * @throws ResponseStatusException if entity not found (404) or FK validation fails (400)
     */
 /*
    public RolesDTO update(RolesDTO dto) {
        logger.debug("update({})", dto);
        
        // Validate DTO
        validateDto(dto);
        
        Integer entityId = getEntityId(dto);
        
        // Check if exists
        if (!repository.existsById(entityId)) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                    String.format("Roles with id %s not found", entityId));
        }
        
        // Validate foreign key references AFTER confirming entity exists
        validateForeignKeyReferences(dto);
        
        Roles entity = dtoToEntity(dto);
        Roles updated = repository.save(entity);
        return entityToDto(updated);
    }
    */
}
