/*
 * Created on 2025-10-25 ( 20:29:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.user.rest.services;

import java.util.List;
import java.util.Optional;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.http.HttpStatus;

import com.mijimoto.ECommerce.user.persistence.entities.UserRoles;
import com.mijimoto.ECommerce.user.persistence.repositories.UserRolesRepository;
import com.mijimoto.ECommerce.user.rest.dto.UserRolesDTO;
import com.mijimoto.ECommerce.common.rest.services.GenericService;

import com.mijimoto.ECommerce.user.persistence.repositories.UsersRepository;
import com.mijimoto.ECommerce.user.persistence.repositories.RolesRepository;

/**
 * REST service for entity "UserRoles" <br>
 *
 * This service provides all the necessary operations required by the REST controller <br>
 * Enhanced to handle foreign key relationships with proper validation and error handling using
 * ResponseStatusException (Option A).
 *
 * @author Telosys
 *
 */
@Service
@Transactional
public class UserRolesService extends GenericService<UserRoles, UserRolesDTO> {

    private static final Logger logger = LoggerFactory.getLogger(UserRolesService.class);

    private final UserRolesRepository repository;

    private final UsersRepository usersRepository;
    private final RolesRepository rolesRepository;

    /**
     * Constructor (usable for Dependency Injection)
     *
     * @param repository the repository to be injected
     * @param usersRepository the Users repository to be injected
     * @param rolesRepository the Roles repository to be injected
     */
    public UserRolesService(UserRolesRepository repository, UsersRepository usersRepository, RolesRepository rolesRepository) {
        super(UserRoles.class, UserRolesDTO.class);
        this.repository = repository;
        this.usersRepository = usersRepository;
        this.rolesRepository = rolesRepository;
    }
    
    /**
     * Returns the entity ID object from the given DTO
     *
     * @param dto the DTO
     * @return the entity ID
     */
    private Integer getEntityId(UserRolesDTO dto) {
        return dto.getId();
    }

    /**
     * Validates foreign key references before persisting
     *
     * @param dto the DTO to validate
     * @throws ResponseStatusException if any FK reference is invalid (HTTP 400)
     */
    private void validateForeignKeyReferences(UserRolesDTO dto) {
        // Validate Users reference
        if (dto.getUserId() != null && !usersRepository.existsById(dto.getUserId())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    String.format("Invalid %s id: %s", "Users", dto.getUserId()));
        }
        // Validate Roles reference
        if (dto.getRoleId() != null && !rolesRepository.existsById(dto.getRoleId())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    String.format("Invalid %s id: %s", "Roles", dto.getRoleId()));
        }
    }

    /**
     * Finds all occurrences of the entity
     *
     * @return list of DTOs
     */
    public List<UserRolesDTO> findAll() {
        logger.debug("findAll()");
        Iterable<UserRoles> all = repository.findAll();
        return entityListToDtoList(all);
    }

    /**
     * Finds the entity identified by the given PK
     *
     * @param id 
     * @return the DTO or null if not found
     */
    public UserRolesDTO findById(Integer id) {
        Integer entityId = id;
        logger.debug("findById({})", entityId);
        Optional<UserRoles> optionalEntity = repository.findById(entityId);
        return entityToDto(optionalEntity);
    }

    /**
     * Finds the entity by ID or throws exception
     *
     * @param id 
     * @return the DTO
     * @throws ResponseStatusException if not found (HTTP 404)
     */
    public UserRolesDTO findByIdOrThrow(Integer id) {
        Integer entityId = id;
        logger.debug("findByIdOrThrow({})", entityId);
        Optional<UserRoles> optionalEntity = repository.findById(entityId);
        if (!optionalEntity.isPresent()) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                    String.format("UserRoles with id %s not found", entityId));
        }
        return entityToDto(optionalEntity.get());
    }

    /**
     * Creates the given entity <br>
     * Validates foreign key references before creating
     *
     * @param dto the DTO to create
     * @return the created DTO with generated ID (if applicable)
     * @throws ResponseStatusException if FK validation fails (HTTP 400)
     */
    public UserRolesDTO create(UserRolesDTO dto) {
        logger.debug("create({})", dto);
        
        // Validate DTO
        validateDto(dto);
        
        // Validate foreign key references FIRST
        validateForeignKeyReferences(dto);
        
        // Auto-generated Primary Key - always create
        UserRoles entity = dtoToEntity(dto);
        UserRoles saved = repository.save(entity);
        return entityToDto(saved);
    }

    /**
     * Updates partially the given entity if it exists <br>
     * Only updates non-null fields from DTO <br>
     * Validates foreign key references for non-null FK fields
     *
     * @param id 
     * @param dto the DTO with fields to update
     * @return the updated DTO
     * @throws ResponseStatusException if entity not found (404) or FK validation fails (400)
     */
    public UserRolesDTO partialUpdate(Integer id, UserRolesDTO dto) {
        Integer entityId = id;
        logger.debug("partialUpdate({}, {})", entityId, dto);
        
        Optional<UserRoles> optionalEntity = repository.findById(entityId);
        if (!optionalEntity.isPresent()) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                    String.format("UserRoles with id %s not found", entityId));
        }
        
        // Validate foreign key references for non-null FK fields
        validateForeignKeyReferences(dto);
        
        UserRoles entity = optionalEntity.get();
        
        // Use GenericService's updateEntityFromDto which skips nulls
        updateEntityFromDto(entity, dto);
        
        UserRoles updated = repository.save(entity);
        return entityToDto(updated);
    }

    /**
     * Deletes an entity by its PK
     *
     * @param id 
     * @throws ResponseStatusException if entity not found (HTTP 404)
     */
    public void deleteById(Integer id) {
        Integer entityId = id;
        logger.debug("deleteById({})", entityId);
        
        if (!repository.existsById(entityId)) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                    String.format("UserRoles with id %s not found", entityId));
        }
        
        repository.deleteById(entityId);
    }

    /**
     * Checks if entity exists by ID
     *
     * @param id 
     * @return true if exists, false otherwise
     */
    public boolean existsById(Integer id) {
        Integer entityId = id;
        return repository.existsById(entityId);
    }

    // -----------------------------------------------------------------------------------------
    // Specific "finders" for foreign key relationships
    // -----------------------------------------------------------------------------------------

    /**
     * Finds entities by Users reference
     *
     * @param userId the Users ID
     * @return list of DTOs
     */
//    public List<UserRolesDTO> findByUsers(Integer userId) {
//        logger.debug("findByUsers({})", userId);
//        List<UserRoles> list = repository.findByUserId(userId);
//        return entityListToDtoList(list);
//    }
    
    /**
     * Finds entities by Roles reference
     *
     * @param roleId the Roles ID
     * @return list of DTOs
     */
//    public List<UserRolesDTO> findByRoles(Integer roleId) {
//        logger.debug("findByRoles({})", roleId);
//        List<UserRoles> list = repository.findByRoleId(roleId);
//        return entityListToDtoList(list);
//    }

    // -----------------------------------------------------------------------------------------
    // DEPRECATED METHODS - Use the improved methods above instead
    // These are kept for backward compatibility but should not be used in new code
    // -----------------------------------------------------------------------------------------
    
    /*
    @Deprecated
    public void save(Integer id, UserRolesDTO dto) {
        // DEPRECATED: This method has been replaced by update() which returns the updated entity
        // and provides better error handling with exceptions
        Integer entityId = id;
        logger.warn("DEPRECATED: save() called with entityId: {}. Use update() instead.", entityId);
        
        validateForeignKeyReferences(dto);
        
        // Force PK in DTO
        dto.setId(id);
        
        repository.save(dtoToEntity(dto));
    }
    */

    /* ------------------------------------------------------------------
     * The full `update()` method was intentionally moved to the end of
     * the file and commented out as requested. Keep it commented while
     * preserving the implementation for easy restoration or reference.
     * ------------------------------------------------------------------ */

   
    /**
     * Updates the given entity if it exists <br>
     * Validates foreign key references before updating
     *
     * @param dto the DTO to update
     * @return the updated DTO
     * @throws ResponseStatusException if entity not found (404) or FK validation fails (400)
     */
 /*
    public UserRolesDTO update(UserRolesDTO dto) {
        logger.debug("update({})", dto);
        
        // Validate DTO
        validateDto(dto);
        
        Integer entityId = getEntityId(dto);
        
        // Check if exists
        if (!repository.existsById(entityId)) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                    String.format("UserRoles with id %s not found", entityId));
        }
        
        // Validate foreign key references AFTER confirming entity exists
        validateForeignKeyReferences(dto);
        
        UserRoles entity = dtoToEntity(dto);
        UserRoles updated = repository.save(entity);
        return entityToDto(updated);
    }
    */
}
