/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.catalogue.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.mijimoto.ECommerce.inventory.rest.dto.*;
import com.mijimoto.ECommerce.order.rest.dto.*;

/**
 * DTO class for "ProductVariants"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class ProductVariantsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   productId;
    private String   sku;
    private String   variantHash;
    private BigDecimal   priceOverride;
    private String   metadata;
    private Boolean   isActive;
    private Boolean   allowBackorder;
    private Date   createdAt;

    //--- LINKS ( RELATIONSHIPS )
    private List<OrderItemsDTO> listOfOrderItems;
    private List<InventoryLevelsDTO> listOfInventoryLevels;
    private List<InventoryTransactionsDTO> listOfInventoryTransactions;
    private List<ProductVariantValuesDTO> listOfProductVariantValues;
    private List<StockReservationsDTO> listOfStockReservations;
    private List<StockReceiptLinesDTO> listOfStockReceiptLines;
    private List<CartItemsDTO> listOfCartItems;
    private List<ProductVariantImagesDTO> listOfProductVariantImages;
    private ProductsDTO products;

}