/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.catalogue.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO class for "ProductAttributeOptions"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class ProductAttributeOptionsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   productId;
    private Integer   attributeId;
    private Integer   attributeOptionId;

    //--- LINKS ( RELATIONSHIPS )
    private AttributesDTO attributes;
    private AttributeOptionsDTO attributeOptions;
    private ProductsDTO products;

}