/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.catalogue.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO class for "ProductVariantValues"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class ProductVariantValuesDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   variantId;
    private Integer   valueId;

    //--- LINKS ( RELATIONSHIPS )
    private VariantOptionValuesDTO variantOptionValues;
    private ProductVariantsDTO productVariants;

}