/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.catalogue.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

/**
 * DTO class for "VariantOptionValues"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class VariantOptionValuesDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   groupId;
    private String   value;
    private String   code;
    private Integer   parentValueId;
    private Integer   position;

    //--- LINKS ( RELATIONSHIPS )
    private List<VariantOptionValuesDTO> listOfVariantOptionValues;
    private List<ProductVariantValuesDTO> listOfProductVariantValues;
    private VariantOptionGroupsDTO variantOptionGroups;
    private VariantOptionValuesDTO variantOptionValues;

}