/*
 * Created on 2025-10-24 ( 00:29:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.catalogue.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "AttributeOptions"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="attribute_options", schema="dbo", catalog="EcommerceDB" )
public class AttributeOptions implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="attribute_id", nullable=false)
    private Integer          attributeId    ;

    @Column(name="value", nullable=false, length=255)
    private String           value    ;

    @Column(name="sort_order")
    private Integer          sortOrder    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="attributeOptions")
    private List<ProductAttributeOptions> listOfProductAttributeOptions;

    @ManyToOne
    @JoinColumn(name="attribute_id", referencedColumnName="id", insertable=false, updatable=false)
    private Attributes attributes;

}