/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.catalogue.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Categories"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="categories", schema="dbo", catalog="EcommerceDB" )
public class Categories implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="parent_id")
    private Integer          parentId    ;

    @Column(name="name", nullable=false, length=255)
    private String           name    ;

    @Column(name="slug", nullable=false, length=255)
    private String           slug    ;

    @Column(name="description", length=2147483647)
    private String           description    ;

    @Column(name="sort_order")
    private Integer          sortOrder    ;

    @Column(name="is_published", nullable=false)
    private Boolean          isPublished    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="parent_id", referencedColumnName="id", insertable=false, updatable=false)
    private Categories categories;

    @OneToMany(mappedBy="categories")
    private List<Products> listOfProducts;

    @OneToMany(mappedBy="categories")
    private List<Categories> listOfCategories;

}