/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.catalogue.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "ProductRelations"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="product_relations", schema="dbo", catalog="EcommerceDB" )
public class ProductRelations implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="product_id", nullable=false)
    private Integer          productId    ;

    @Column(name="related_product_id", nullable=false)
    private Integer          relatedProductId    ;

    @Column(name="relation_type", nullable=false, length=20)
    private String           relationType    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products;

    @ManyToOne
    @JoinColumn(name="related_product_id", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products2;

}