/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.catalogue.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.mijimoto.ECommerce.customer.persistence.entities.*;


import jakarta.persistence.*;

/**
 * JPA entity class for "Products"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="products", schema="dbo", catalog="EcommerceDB" )
public class Products implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="sku", length=100)
    private String           sku    ;

    @Column(name="name", nullable=false, length=255)
    private String           name    ;

    @Column(name="slug", nullable=false, length=255)
    private String           slug    ;

    @Column(name="short_description", length=1000)
    private String           shortDescription    ;

    @Column(name="long_description", length=2147483647)
    private String           longDescription    ;

    @Column(name="category_id")
    private Integer          categoryId    ;

    @Column(name="price", nullable=false)
    private BigDecimal       price    ;

    @Column(name="has_variants", nullable=false)
    private Boolean          hasVariants    ;

    @Column(name="is_published", nullable=false)
    private Boolean          isPublished    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date             updatedAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="category_id", referencedColumnName="id", insertable=false, updatable=false)
    private Categories categories;

    @OneToMany(mappedBy="products")
    private List<ProductVariants> listOfProductVariants;

    @OneToMany(mappedBy="products")
    private List<ProductReviews> listOfProductReviews;

    @OneToMany(mappedBy="products")
    private List<ProductAttributeOptions> listOfProductAttributeOptions;

    @OneToMany(mappedBy="products")
    private List<ProductAttributeValues> listOfProductAttributeValues;

    @OneToMany(mappedBy="products")
    private List<ProductRelations> listOfProductRelations;

    @OneToMany(mappedBy="products")
    private List<WishlistItems> listOfWishlistItems;

    @OneToMany(mappedBy="products")
    private List<ProductImages> listOfProductImages;

    @OneToMany(mappedBy="products2")
    private List<ProductRelations> listOfProductRelations2;

    @OneToMany(mappedBy="products")
    private List<VariantOptionGroups> listOfVariantOptionGroups;

}