/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.catalogue.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "ProductVariantImages"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="product_variant_images", schema="dbo", catalog="EcommerceDB" )
public class ProductVariantImages implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="variant_id", nullable=false)
    private Integer          variantId    ;

    @Column(name="url", nullable=false, length=2000)
    private String           url    ;

    @Column(name="is_primary", nullable=false)
    private Boolean          isPrimary    ;

    @Column(name="sort_order")
    private Integer          sortOrder    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="variant_id", referencedColumnName="id", insertable=false, updatable=false)
    private ProductVariants productVariants;

}