/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.catalogue.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "VariantOptionValues"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="variant_option_values", schema="dbo", catalog="EcommerceDB" )
public class VariantOptionValues implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="group_id", nullable=false)
    private Integer          groupId    ;

    @Column(name="value", nullable=false, length=255)
    private String           value    ;

    @Column(name="code", length=255)
    private String           code    ;

    @Column(name="parent_value_id")
    private Integer          parentValueId    ;

    @Column(name="position")
    private Integer          position    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="variantOptionValues")
    private List<VariantOptionValues> listOfVariantOptionValues;

    @OneToMany(mappedBy="variantOptionValues")
    private List<ProductVariantValues> listOfProductVariantValues;

    @ManyToOne
    @JoinColumn(name="group_id", referencedColumnName="id", insertable=false, updatable=false)
    private VariantOptionGroups variantOptionGroups;

    @ManyToOne
    @JoinColumn(name="parent_value_id", referencedColumnName="id", insertable=false, updatable=false)
    private VariantOptionValues variantOptionValues;

}