/*
 * Created on 2025-10-24 ( 00:29:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.user.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import java.util.List;

import com.mijimoto.ECommerce.order.persistence.entities.Orders;
import com.mijimoto.ECommerce.shipping.persistence.entities.Countries;
import com.mijimoto.ECommerce.shipping.persistence.entities.Provinces;

import jakarta.persistence.*;

/**
 * JPA entity class for "Addresses"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="addresses", schema="dbo", catalog="EcommerceDB" )
public class Addresses implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="user_id", nullable=false)
    private Integer          userId    ;

    @Column(name="label", length=255)
    private String           label    ;

    @Column(name="recipient_name", length=255)
    private String           recipientName    ;

    @Column(name="phone_id")
    private Integer          phoneId    ;

    @Column(name="address_line", nullable=false, length=1000)
    private String           addressLine    ;

    @Column(name="province_id")
    private Integer          provinceId    ;

    @Column(name="country_id")
    private Integer          countryId    ;

    @Column(name="postal_code", length=50)
    private String           postalCode    ;

    @Column(name="is_default", nullable=false)
    private Boolean          isDefault    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="country_id", referencedColumnName="id", insertable=false, updatable=false)
    private Countries  countries;

    @ManyToOne
    @JoinColumn(name="province_id", referencedColumnName="id", insertable=false, updatable=false)
    private Provinces  provinces;

    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id", insertable=false, updatable=false)
    private Users      users;

    @OneToMany(mappedBy="addresses")
    private List<Orders> listOfOrders;

    @ManyToOne
    @JoinColumn(name="phone_id", referencedColumnName="id", insertable=false, updatable=false)
    private UserPhoneNumbers userPhoneNumbers;

}