/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.user.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "UserPhoneNumbers"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="user_phone_numbers", schema="dbo", catalog="EcommerceDB" )
public class UserPhoneNumbers implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="user_id", nullable=false)
    private Integer          userId    ;

    @Column(name="phone_number", nullable=false, length=50)
    private String           phoneNumber    ;

    @Column(name="phone_type", length=20)
    private String           phoneType    ;

    @Column(name="is_primary", nullable=false)
    private Boolean          isPrimary    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="userPhoneNumbers")
    private List<Addresses> listOfAddresses;

    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id", insertable=false, updatable=false)
    private Users      users;

}