/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.order.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.Date;

import com.mijimoto.ECommerce.catalogue.rest.dto.ProductVariantsDTO;

/**
 * DTO class for "CartItems"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class CartItemsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   cartId;
    private Integer   variantId;
    private Integer   quantity;
    private BigDecimal   unitPrice;
    private String   metadata;
    private Date   addedAt;

    //--- LINKS ( RELATIONSHIPS )
    private ShoppingCartsDTO shoppingCarts;
    private ProductVariantsDTO productVariants;

}