/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.order.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

import com.mijimoto.ECommerce.user.rest.dto.UsersDTO;

/**
 * DTO class for "CouponRedemptions"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class CouponRedemptionsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id;

    //--- OTHER DATA FIELDS 
    private Integer   couponId;
    private Integer   userId;
    private Long   orderId;
    private Date   usedAt;

    //--- LINKS ( RELATIONSHIPS )
    private OrdersDTO orders;
    private UsersDTO users;
    private CouponsDTO coupons;

}