/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.order.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

import com.mijimoto.ECommerce.catalogue.rest.dto.ProductVariantsDTO;

/**
 * DTO class for "OrderItems"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class OrderItemsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id;

    //--- OTHER DATA FIELDS 
    private Long   orderId;
    private Integer   variantId;
    private String   productSnapshotName;
    private String   skuSnapshot;
    private BigDecimal   unitPrice;
    private Integer   quantity;
    private BigDecimal   lineTotal;

    //--- LINKS ( RELATIONSHIPS )
    private ProductVariantsDTO productVariants;
    private OrdersDTO orders;

}