/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.order.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.Date;

/**
 * DTO class for "OrderPayments"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class OrderPaymentsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id;

    //--- OTHER DATA FIELDS 
    private Long   orderId;
    private String   provider;
    private String   providerTransactionId;
    private BigDecimal   amount;
    private String   currency;
    private String   status;
    private String   rawResponse;
    private Date   createdAt;

    //--- LINKS ( RELATIONSHIPS )
    private OrdersDTO orders;

}