/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.common.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

import com.mijimoto.ECommerce.user.rest.dto.UsersDTO;

/**
 * DTO class for "AuditLogs"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class AuditLogsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id;

    //--- OTHER DATA FIELDS 
    private Integer   userId;
    private String   action;
    private String   objectType;
    private String   objectId;
    private String   details;
    private Date   createdAt;

    //--- LINKS ( RELATIONSHIPS )
    private UsersDTO users;

}