/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.shipping.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

import com.mijimoto.ECommerce.user.persistence.entities.Addresses;

import jakarta.persistence.*;

/**
 * JPA entity class for "Provinces"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="provinces", schema="dbo", catalog="EcommerceDB" )
public class Provinces implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="country_id", nullable=false)
    private Integer          countryId    ;

    @Column(name="name", nullable=false, length=255)
    private String           name    ;

    @Column(name="code", length=50)
    private String           code    ;

    @Column(name="shipping_zone_id")
    private Integer          shippingZoneId    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="shipping_zone_id", referencedColumnName="id", insertable=false, updatable=false)
    private ShippingZones shippingZones;

    @ManyToOne
    @JoinColumn(name="country_id", referencedColumnName="id", insertable=false, updatable=false)
    private Countries  countries;

    @OneToMany(mappedBy="provinces")
    private List<Addresses> listOfAddresses;

}