/*
 * Created on 2025-10-24 ( 00:32:17 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.persistence.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import com.mijimoto.ECommerce.persistence.entities.UserRoles;

/**
 * Spring Data JPA repository for entity "UserRoles" <br>
 *
 * This repository extends JpaRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 *   findById, findAll, save, delete, etc <br>
 * with pagination and sorting : <br>
 *   findAll(Pageable), findAll(Sort)<br>
 *
 * This repository can be extended by adding specific "finder" methods.<br>
 * For custom queries, follow Spring Data JPA derived query method conventions.
 *
 * @author Telosys
 */
public interface UserRolesRepository extends JpaRepository<UserRoles, Integer> {

    // -- Add your custom finder methods below --

    // Example: Find by a String field
    // List<UserRoles> findByXxx(String xxx);

    // Example: Find by a field with LIKE behavior
    // List<UserRoles> findByXxxContaining(String xxx);

    // Example: Find by a numerical field
    // List<UserRoles> findByYyy(BigDecimal yyy);

    // Example: Find by foreign key (like PartID)
    // List<UserRoles> findByPartID(Integer partID); // Use Optional<> or single result for OneToOne

}
