/*
 * Created on 2025-10-24 ( 00:29:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Attributes"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="attributes", schema="dbo", catalog="EcommerceDB" )
public class Attributes implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="name", nullable=false, length=255)
    private String           name    ;

    @Column(name="code", length=255)
    private String           code    ;

    @Column(name="value_type", length=50)
    private String           valueType    ;

    @Column(name="is_variant_defining", nullable=false)
    private Boolean          isVariantDefining    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="attributes")
    private List<AttributeOptions> listOfAttributeOptions;

    @OneToMany(mappedBy="attributes")
    private List<ProductAttributeOptions> listOfProductAttributeOptions;

    @OneToMany(mappedBy="attributes")
    private List<ProductAttributeValues> listOfProductAttributeValues;

}