/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "CartItems"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="cart_items", schema="dbo", catalog="EcommerceDB" )
public class CartItems implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="cart_id", nullable=false)
    private Integer          cartId    ;

    @Column(name="variant_id", nullable=false)
    private Integer          variantId    ;

    @Column(name="quantity", nullable=false)
    private Integer          quantity    ;

    @Column(name="unit_price", nullable=false)
    private BigDecimal       unitPrice    ;

    @Column(name="metadata", length=2147483647)
    private String           metadata    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="added_at", nullable=false)
    private Date             addedAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="cart_id", referencedColumnName="id", insertable=false, updatable=false)
    private ShoppingCarts shoppingCarts;

    @ManyToOne
    @JoinColumn(name="variant_id", referencedColumnName="id", insertable=false, updatable=false)
    private ProductVariants productVariants;

}