/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Countries"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="countries", schema="dbo", catalog="EcommerceDB" )
public class Countries implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="name", nullable=false, length=255)
    private String           name    ;

    @Column(name="iso_code", length=10)
    private String           isoCode    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="countries")
    private List<Provinces> listOfProvinces;

    @OneToMany(mappedBy="countries")
    private List<Addresses> listOfAddresses;

}