/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Coupons"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="coupons", schema="dbo", catalog="EcommerceDB" )
public class Coupons implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="code", nullable=false, length=100)
    private String           code    ;

    @Column(name="discount_type", nullable=false, length=20)
    private String           discountType    ;

    @Column(name="value", nullable=false)
    private BigDecimal       value    ;

    @Column(name="min_subtotal")
    private BigDecimal       minSubtotal    ;

    @Column(name="usage_limit")
    private Integer          usageLimit    ;

    @Column(name="used_count", nullable=false)
    private Integer          usedCount    ;

    @Column(name="per_user_limit")
    private Integer          perUserLimit    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="valid_from")
    private Date             validFrom    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="valid_to")
    private Date             validTo    ;

    @Column(name="is_active", nullable=false)
    private Boolean          isActive    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="coupons")
    private List<CouponRedemptions> listOfCouponRedemptions;

    @OneToMany(mappedBy="coupons")
    private List<Orders> listOfOrders;

}