/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "CouponRedemptions"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="coupon_redemptions", schema="dbo", catalog="EcommerceDB" )
public class CouponRedemptions implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="coupon_id", nullable=false)
    private Integer          couponId    ;

    @Column(name="user_id", nullable=false)
    private Integer          userId    ;

    @Column(name="order_id")
    private Long             orderId    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="used_at", nullable=false)
    private Date             usedAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="order_id", referencedColumnName="id", insertable=false, updatable=false)
    private Orders     orders;

    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id", insertable=false, updatable=false)
    private Users      users;

    @ManyToOne
    @JoinColumn(name="coupon_id", referencedColumnName="id", insertable=false, updatable=false)
    private Coupons    coupons;

}