/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "OrderEvents"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="order_events", schema="dbo", catalog="EcommerceDB" )
public class OrderEvents implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id;

    //--- OTHER DATA FIELDS 
    @Column(name="order_id", nullable=false)
    private Long             orderId    ;

    @Column(name="event_type", nullable=false, length=50)
    private String           eventType    ;

    @Column(name="actor_id")
    private Integer          actorId    ;

    @Column(name="details", length=2147483647)
    private String           details    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="actor_id", referencedColumnName="id", insertable=false, updatable=false)
    private Users      users;

    @ManyToOne
    @JoinColumn(name="order_id", referencedColumnName="id", insertable=false, updatable=false)
    private Orders     orders;

}