/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "ProductVariants"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="product_variants", schema="dbo", catalog="EcommerceDB" )
public class ProductVariants implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="product_id", nullable=false)
    private Integer          productId    ;

    @Column(name="sku", nullable=false, length=100)
    private String           sku    ;

    @Column(name="variant_hash", length=200)
    private String           variantHash    ;

    @Column(name="price_override")
    private BigDecimal       priceOverride    ;

    @Column(name="metadata", length=2147483647)
    private String           metadata    ;

    @Column(name="is_active", nullable=false)
    private Boolean          isActive    ;

    @Column(name="allow_backorder", nullable=false)
    private Boolean          allowBackorder    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="productVariants")
    private List<OrderItems> listOfOrderItems;

    @OneToMany(mappedBy="productVariants")
    private List<InventoryLevels> listOfInventoryLevels;

    @OneToMany(mappedBy="productVariants")
    private List<InventoryTransactions> listOfInventoryTransactions;

    @OneToMany(mappedBy="productVariants")
    private List<ProductVariantValues> listOfProductVariantValues;

    @OneToMany(mappedBy="productVariants")
    private List<StockReservations> listOfStockReservations;

    @OneToMany(mappedBy="productVariants")
    private List<StockReceiptLines> listOfStockReceiptLines;

    @OneToMany(mappedBy="productVariants")
    private List<CartItems> listOfCartItems;

    @OneToMany(mappedBy="productVariants")
    private List<ProductVariantImages> listOfProductVariantImages;

    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products;

}