/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "ProductAttributeValues"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="product_attribute_values", schema="dbo", catalog="EcommerceDB" )
public class ProductAttributeValues implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="product_id", nullable=false)
    private Integer          productId    ;

    @Column(name="attribute_id", nullable=false)
    private Integer          attributeId    ;

    @Column(name="value", length=1000)
    private String           value    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products;

    @ManyToOne
    @JoinColumn(name="attribute_id", referencedColumnName="id", insertable=false, updatable=false)
    private Attributes attributes;

}