/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import jakarta.persistence.*;

/**
 * JPA entity class for "ShippingRates"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="shipping_rates", schema="dbo", catalog="EcommerceDB" )
public class ShippingRates implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="shipping_zone_id", nullable=false)
    private Integer          shippingZoneId    ;

    @Column(name="min_weight")
    private BigDecimal       minWeight    ;

    @Column(name="max_weight")
    private BigDecimal       maxWeight    ;

    @Column(name="price", nullable=false)
    private BigDecimal       price    ;

    @Column(name="carrier", length=255)
    private String           carrier    ;

    @Column(name="service_level", length=255)
    private String           serviceLevel    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="shipping_zone_id", referencedColumnName="id", insertable=false, updatable=false)
    private ShippingZones shippingZones;

}