/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "StockReservations"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="stock_reservations", schema="dbo", catalog="EcommerceDB" )
public class StockReservations implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="order_id")
    private Long             orderId    ;

    @Column(name="variant_id", nullable=false)
    private Integer          variantId    ;

    @Column(name="warehouse_id")
    private Integer          warehouseId    ;

    @Column(name="quantity", nullable=false)
    private Integer          quantity    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expires_at")
    private Date             expiresAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    @Column(name="reason", length=255)
    private String           reason    ;

    @Column(name="is_active", nullable=false)
    private Boolean          isActive    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="variant_id", referencedColumnName="id", insertable=false, updatable=false)
    private ProductVariants productVariants;

    @ManyToOne
    @JoinColumn(name="warehouse_id", referencedColumnName="id", insertable=false, updatable=false)
    private Warehouses warehouses;

    @ManyToOne
    @JoinColumn(name="order_id", referencedColumnName="id", insertable=false, updatable=false)
    private Orders     orders;

}