/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import jakarta.persistence.*;

/**
 * JPA entity class for "StockReceiptLines"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="stock_receipt_lines", schema="dbo", catalog="EcommerceDB" )
public class StockReceiptLines implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="receipt_id", nullable=false)
    private Integer          receiptId    ;

    @Column(name="variant_id", nullable=false)
    private Integer          variantId    ;

    @Column(name="warehouse_id")
    private Integer          warehouseId    ;

    @Column(name="quantity", nullable=false)
    private Integer          quantity    ;

    @Column(name="cost_price")
    private BigDecimal       costPrice    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="receipt_id", referencedColumnName="id", insertable=false, updatable=false)
    private StockReceipts stockReceipts;

    @ManyToOne
    @JoinColumn(name="variant_id", referencedColumnName="id", insertable=false, updatable=false)
    private ProductVariants productVariants;

    @ManyToOne
    @JoinColumn(name="warehouse_id", referencedColumnName="id", insertable=false, updatable=false)
    private Warehouses warehouses;

}