/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "UserRoles"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="user_roles", schema="dbo", catalog="EcommerceDB" )
public class UserRoles implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="user_id", nullable=false)
    private Integer          userId    ;

    @Column(name="role_id", nullable=false)
    private Integer          roleId    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id", insertable=false, updatable=false)
    private Users      users;

    @ManyToOne
    @JoinColumn(name="role_id", referencedColumnName="id", insertable=false, updatable=false)
    private Roles      roles;

}