/*
 * Created on 2025-10-24 ( 00:29:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "VariantOptionGroups"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="variant_option_groups", schema="dbo", catalog="EcommerceDB" )
public class VariantOptionGroups implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id;

    //--- OTHER DATA FIELDS 
    @Column(name="product_id")
    private Integer          productId    ;

    @Column(name="name", nullable=false, length=255)
    private String           name    ;

    @Column(name="position")
    private Integer          position    ;

    @Column(name="is_required", nullable=false)
    private Boolean          isRequired    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="variantOptionGroups")
    private List<VariantOptionValues> listOfVariantOptionValues;

    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id", insertable=false, updatable=false)
    private Products   products;

}