/*
 * Created on 2025-10-24 ( 00:34:11 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.mijimoto.ECommerce.inventory.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

import com.mijimoto.ECommerce.catalogue.rest.dto.ProductVariantsDTO;

/**
 * DTO class for "InventoryTransactions"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class InventoryTransactionsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id;

    //--- OTHER DATA FIELDS 
    private Integer   variantId;
    private Integer   warehouseId;
    private Integer   quantityChange;
    private String   reason;
    private String   reference;
    private Date   createdAt;

    //--- LINKS ( RELATIONSHIPS )
    private ProductVariantsDTO productVariants;
    private WarehousesDTO warehouses;

}