/*
 * Created on 2025-10-24 ( 00:29:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.mijimoto.ECommerce.common.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

import com.mijimoto.ECommerce.user.persistence.entities.Users;

import jakarta.persistence.*;

/**
 * JPA entity class for "AuditLogs"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="audit_logs", schema="dbo", catalog="EcommerceDB" )
public class AuditLogs implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id;

    //--- OTHER DATA FIELDS 
    @Column(name="user_id")
    private Integer          userId    ;

    @Column(name="action", nullable=false, length=255)
    private String           action    ;

    @Column(name="object_type", length=255)
    private String           objectType    ;

    @Column(name="object_id", length=255)
    private String           objectId    ;

    @Column(name="details", length=2147483647)
    private String           details    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date             createdAt    ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id", insertable=false, updatable=false)
    private Users      users;

}